In [1]:
import numpy as np

# 넘파이는 dynamic type을 지원하지 않음
### c와 호환 가능한 데이터 타입이기 때문에 byte를 중요하게 생각하자!

In [7]:
test_array = np.array(["1","4",5,8], float)
# test_array = np.array(["1","4",5,8], np.str)
print(test_array)
print(type(test_array))
print(type(test_array[1]))

[1. 4. 5. 8.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [9]:
test_array.dtype

dtype('float64')

In [11]:
test_array.shape

(4,)

## 파이썬 리스트는 주소값을 저장해서 for loop을 했을 때 속도저하가 크다.

In [22]:
tensor = [
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
]
print(np.array(tensor, int).shape,'\n',
      np.array(tensor, int).ndim,'\n',
      np.array(tensor, int).size,'\n',
      np.array(tensor, int).nbytes)

(4, 3, 4) 
 3 
 48 
 192


# reshape array size만 같다면

In [24]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [25]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [26]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [28]:
np.array(test_matrix).reshape(-1, 2).shape # -1은 size를 기반으로 row 개수 선정

(4, 2)

In [31]:
a = np.array(test_matrix).reshape(2,2,2)
a.size

8

In [33]:
a.reshape(1,1,-1,2)

array([[[[1, 2],
         [3, 4],
         [1, 2],
         [5, 8]]]])

In [34]:
a.flatten()

array([1, 2, 3, 4, 1, 2, 5, 8])

# indexing & slicing

In [35]:
test_matrix = np.array([[1,2,3], [4.5, 5, 6]], int)
test_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
test_matrix[0][0]

1

In [38]:
test_matrix[0, 0] = 5
test_matrix[0, 0]

5

In [39]:
test_matrix = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)

In [43]:
test_matrix[:, 2:] # 전체 row 부분 col

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [44]:
test_matrix[1,1:3] # row col

array([7, 8])

In [45]:
test_matrix[1:3] # row

array([[ 6,  7,  8,  9, 10]])

In [46]:
test_matrix = np.array([[1,2,5,8],
                        [1,2,5,8],
                        [1,2,5,8],
                        [1,2,5,8]], int)

In [47]:
test_matrix[1, 2:]

array([5, 8])

# numpy creation

In [48]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [52]:
np.arange(0, 5, 0.2).tolist()

[0.0,
 0.2,
 0.4,
 0.6000000000000001,
 0.8,
 1.0,
 1.2000000000000002,
 1.4000000000000001,
 1.6,
 1.8,
 2.0,
 2.2,
 2.4000000000000004,
 2.6,
 2.8000000000000003,
 3.0,
 3.2,
 3.4000000000000004,
 3.6,
 3.8000000000000003,
 4.0,
 4.2,
 4.4,
 4.6000000000000005,
 4.800000000000001]

In [54]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [55]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [56]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
np.ones_like(test_matrix) # shape을 가져와서 1, 0, empty 채우기

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [61]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
np.eye(N=3, M=5, k=1) # ㅏ= start point

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [70]:
print(test_matrix)
np.diag(test_matrix, k=1)

[[1 2 5 8]
 [1 2 5 8]
 [1 2 5 8]
 [1 2 5 8]]


array([2, 5, 8])

In [74]:
np.random.uniform(0,5,10).reshape(2,5) #균등분표

array([[3.52344157, 4.7006442 , 1.25104982, 3.87198843, 4.78112416],
       [0.3525009 , 2.76642179, 4.84650944, 1.71175918, 1.34460708]])

In [75]:
np.random.normal(0,5,10).reshape(2,5) #정규분표

array([[ 3.73982518,  0.48990374,  1.83108258, -1.66509043, -0.93784219],
       [ 0.8838377 , -7.07049538,  4.41523335,  2.69788472,  1.26942822]])

# numpy operation

In [77]:
test_array = np.arange(1,11)
test_array.sum(dtype=np.float)

55.0

In [79]:
test_array = np.arange(1,13).reshape(3,4)
print(test_array)
test_array.sum(axis=1), test_array.sum(axis=0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(array([10, 26, 42]), array([15, 18, 21, 24]))

In [84]:
tensor = np.array([[[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]],
                   
                    [[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]],
                    
                   [[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]]])

In [89]:
tensor.sum()

234

In [90]:
tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [91]:
tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [92]:
tensor.sum(axis=2) 

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [93]:
print(test_array)
test_array.mean(), test_array.std(axis=1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(6.5, array([1.11803399, 1.11803399, 1.11803399]))

In [94]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [95]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [96]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [98]:
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6])

In [101]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

# array operation

In [103]:
test_array = np.array([[1,2,3], [4,5,6]])

In [104]:
test_array + test_array

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [107]:
test_array * test_array # element-wise operations * array shape 같아야함

array([[ 1,  4,  9],
       [16, 25, 36]])

In [109]:
test_array.dot(test_array.T)

array([[14, 32],
       [32, 77]])

In [114]:
scalar = 3
test_array * scalar
test_array // scalar#broadcasting

array([[0, 0, 1],
       [1, 1, 2]], dtype=int32)

In [120]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)

In [121]:
test_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [122]:
test_vector

array([10, 20, 30])

In [123]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### 속도비교

In [124]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

_iter = 100000000

vector = list(range(_iter))
scalar = 2

%timeit scalar_vector_product(scalar, vector)

58.6 s ± 6.62 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [125]:
%timeit [scalar * value for value in range(_iter)]

28.2 s ± 1.63 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [129]:
%timeit np.arange(_iter) * scalar

984 ms ± 53.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# comparison

In [133]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
np.any(a>5), np.any(a<0) #하나라도 조건에 만족한다면

(False, False)

In [132]:
np.all(a>5), np.all(a<10) 

(False, True)

In [134]:
a<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [136]:
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b

array([False,  True, False])

In [137]:
np.logical_and(a>0, a<3) #or, not xor도 있음

array([False,  True,  True, False, False, False, False, False, False,
       False])

In [147]:
np.where(a>5, 1, 0) # index값 반환 true, false 파라미터

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [148]:
np.isnan(np.array([1, np.NaN]))

array([False,  True])

In [149]:
np.isinf(np.array([1, np.inf]))

array([False,  True])

In [154]:
a=a.reshape(5,2)
print(a)
np.argmax(a), np.argmin(a), np.argmax(a, axis=0), np.argmin(a, axis=0) # index반환

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


(9, 0, array([4, 4], dtype=int64), array([0, 0], dtype=int64))

# boolean & fancy index

In [162]:
a = a.flatten()
condition = a > 3

In [163]:
a[condition]

array([4, 5, 6, 7, 8, 9])

In [164]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) # 반드시 integer
a[b] # b의 인덱스로 에이값출력

array([2., 2., 4., 8., 6., 4.])

In [165]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [166]:
a = np.array([[1,4], [9,16]], float)
b = np.array([0,0,0,1,1])
c = np.array([0,1,1,0,1])
a[b,c]

array([ 1.,  4.,  4.,  9., 16.])

In [167]:
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.]])

# numpy data i/o

In [173]:
np.savetxt("np_test.txt", a, delimiter=" ")

In [175]:
a = np.loadtxt("./np_test.txt", dtype=int)
a

array([[ 1,  4],
       [ 9, 16]])

In [177]:
np.save("npy_test", a)

In [179]:
npy = np.load("npy_test.npy")
npy

array([[ 1,  4],
       [ 9, 16]])